name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  thank-user:
    runs-on: ubuntu-latest
    name: Say thanks for the PR
    steps:
      - name: Comment on PR
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          REPO_TOKEN: ${{ secrets.CLI_BOT }}
        run: |
          message='Thank you for your contribution! We will review the pull request and get back to you soon.'
          # Comment on the PR using GitHub API
          curl -X POST \
            -H "Authorization: token $REPO_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"$message\"}"
  build:
    name: 'Terraform Init, Fmt, and Plan'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
    - name: Terraform Init
      run: terraform init

    - name: Terraform Format check
      run: terraform fmt --recursive

    - name: Terraform Plan
      run: terraform plan -input=false
      env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
